CREATE TABLE EMPLEADOS(
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DNI VARCHAR(10) NOT  NULL,
    NOMBRE VARCHAR(250) NOT  NULL,
    APELLIDOS VARCHAR(250) NOT  NULL,
    CORREO VARCHAR(250) UNIQUE,
    CLAVE VARCHAR(30) DEFAULT '1234',
    CARGO VARCHAR(250) NOT  NULL,
    ADMINISTRADOR BOOLEAN  NOT NULL DEFAULT FALSE,
    ACTIVO BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (ID)
);

CREATE TABLE HORARIO(
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    IDEMPLEADO INTEGER NOT  NULL,
    FECHA DATE,
    HORAINICIO TIME,
    HORAFIN TIME,
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADOS(ID)
);

INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDOS, CORREO, CARGO)
VALUES ('879675Y', 'Ana', 'Florian', 'aflorian@gmail.com', 'Administradora'),
('464674Y', 'Javier', 'Perez', 'jperez@gmail.com', 'Gerente'),
('57575Y', 'Eugenio', 'Peinado', 'epeinado@gmail.com', 'Asistente');

INSERT INTO HORARIO(IDEMPLEADO)
VALUES (1), (2), (3);

SELECT * FROM APP.EMPLEADOS ;
SELECT * FROM APP.HORARIO;

